name: laboratory
channels:
  - apple
  - conda-forge
dependencies:
  - black=21.7b0
  - flake8=4.0.1
  - isort=5.9.3
  - jupyter=1.0.0
  - matplotlib=3.4.3
  - numpy=1.19.5
  - pandas=1.3.4
  - pip=21.3.1
  - pre-commit=2.15.0
  - pytest=6.2.5
  - python=3.9.7
  - scikit-learn=1.0
  - tensorboard=2.6.0
  - tensorflow-deps=2.6.0
  - testbook=0.4.2
  - tqdm=4.62.3
  - pip:
    - tensorflow-macos==2.6.0
    - tensorflow-metal==0.2.0
